spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**
            - id: booking-service
              uri: http://localhost:8081
              predicates:
                - Path=/booking/**
            - id: notification-service
              uri: http://localhost:8082
              predicates:
                - Path=/notification/**
            - id: room-service
              uri: http://localhost:8083
              predicates:
                - Path=/room/**

server:
  port: 8765

jwt:
  secret: ${JWT_SECRET}
