<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.shelter</groupId>
        <artifactId>shelter</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>liquibase</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <configuration>
                    <propertyFile>local.properties</propertyFile>
                    <driver>org.postgresql.Driver</driver>
                    <changeLogFile>db/changelog/db.changelog-master.xml</changeLogFile>
                    <searchPath>${project.basedir}/src/main/resources</searchPath>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
